project/app/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.HomeView.as_view(), name="home"),
    path("signup/", views.signup, name="signup"),
    path("users/<int:pk>/", views.UserDetailView.as_view(), name="users_detail"),
    path("users/<int:pk>/update/", views.UserUpdateView.as_view(), name="users_update"),
    path("users/<int:pk>/delete/", views.UserDeleteView.as_view(), name="users_delete"),
    path("lists/", views.ListListView.as_view(), name="lists_list"),
    path("lists/create/", views.ListCreateView.as_view(), name="lists_create"),
    path("lists/<int:pk>/", views.ListDetailView.as_view(), name="lists_detail"),
    path("lists/<int:pk>/update/", views.ListUpdateView.as_view(), name="lists_update"),
    path("lists/<int:pk>/delete/", views.ListDeleteView.as_view(), name="lists_delete"),
    path("cards/create/", views.CardCreateView.as_view(), name="cards_create"),
    path("cards/", views.CardListView.as_view(), name="cards_list"),
    path("cards/<int:pk>/", views.CardDetailView.as_view(), name="cards_detail"),
    path("cards/<int:pk>/update/", views.CardUpdateView.as_view(), name="cards_update"),
    path("cards/<int:pk>/delete/", views.CardDeleteView.as_view(), name="cards_delete"),
    path("cards/create/<int:list_pk>", views.CardCreateFromHomeView.as_view(), name="cards_create_from_home"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('', include('django.contrib.auth.urls')),
]

project/app/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class List(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Card(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    list = models.ForeignKey(List, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

project/app/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import DetailView, UpdateView, DeleteView, CreateView, ListView
from .form import UserForm, ListForm, CardForm, CardCreateFromHomeForm
from .mixins import OnlyYouMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . models import List, Card

# Create your views here.

def index(request):
    return render(request, "app/index.html")

def home(request):
    return render(request, "app/home.html")

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("app:home")
    else:
        form = UserCreationForm()

    context = {
        "form": form
    }
    return render(request, 'app/signup.html', context)

class HomeView(LoginRequiredMixin, ListView):
    model = List
    template_name = "app/home.html"

class UserDetailView(DetailView):
    model = User
    template_name = "app/users/detail.html"

class UserUpdateView(OnlyYouMixin, UpdateView):
    model = User
    template_name = "app/users/update.html"
    form_class = UserForm
    def get_success_url(self):
        return resolve_url('app:users_detail', pk=self.kwargs['pk'])

class UserDeleteView(OnlyYouMixin, DeleteView):
    model = User
    template_name = "app/users/delete.html"

    def get_success_url(self):
        return resolve_url('app:index')

class ListCreateView(LoginRequiredMixin, CreateView):
    model = List
    template_name = "app/lists/create.html"
    form_class = ListForm
    success_url = reverse_lazy("app:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ListListView(LoginRequiredMixin, ListView):
    model = List
    template_name = "app/lists/list.html"

class ListDetailView(LoginRequiredMixin, DetailView):
    model = List
    template_name = "app/lists/detail.html"

class ListUpdateView(LoginRequiredMixin, UpdateView):
    model = List
    template_name = "app/lists/update.html"
    form_class = ListForm

    def get_success_url(self):
        return resolve_url('app:home', pk=self.kwargs['pk'])

class ListDeleteView(LoginRequiredMixin, DeleteView):
    model = List
    template_name = "app/lists/delete.html"
    form_class = ListForm
    success_url = reverse_lazy("app:home")

class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    template_name = "app/cards/create.html"
    form_class = CardForm
    success_url = reverse_lazy("app:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CardListView(LoginRequiredMixin, ListView):
    model = Card
    template_name = "app/cards/list.html"

class CardDetailView(LoginRequiredMixin, DetailView):
    model = Card
    template_name = "app/cards/detail.html"

class CardUpdateView(LoginRequiredMixin, UpdateView):
    model = Card
    template_name = "app/cards/update.html"
    form_class = CardForm

    def get_success_url(self):
        return resolve_url('app:home', pk=self.kwargs['pk'])

class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = Card
    template_name = "app/cards/delete.html"
    form_class = CardForm
    success_url = reverse_lazy("app:home")

class CardCreateFromHomeView(LoginRequiredMixin, CreateView):
    model = Card
    template_name = "app/cards/create.html"
    form_class = CardCreateFromHomeForm
    success_url = reverse_lazy("app:home")

    def form_valid(self, form):
        list_pk = self.kwargs['list_pk']
        list_instance = get_object_or_404(List, pk=list_pk)
        form.instance.list = list_instance
        form.instance.user = self.request.user
        return super().form_valid(form)

project/app/templates/app/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'app/custom.css' %}">
    <title>TODO-Share</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-primary navbar-fixed-top">
        {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'app:home' %}"><span class="fas fa-edit"></span>TODO-Share</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'app:index' %}"><span class="fas fa-edit"></span>TODO-Share</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:users_detail' request.user.pk %}">{{ request.user.username }}</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:lists_list' %}">リスト一覧</a>
            </li>
            <li class="nav-item">
             <a class="nav-link" href="{% url 'app:cards_list' %}">タスク一覧</a>
           </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:signup' %}">サインアップ</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

project/app/templates/app/cards/create.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>タスク作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

project/app/templates/app/cards/delete.html
{% extends "app/base.html" %}

{% block content %}
<h1>タスク削除</h1>
<div class="container">
  <form method="post">
    {% csrf_token %}
    <p>タスク "{{ card.title }}" を本当に削除してもよろしいですか？</p>
    <button type="submit" class="btn btn-danger">確認</button>
  </form>
</div>
{% endblock %}

project/app/templates/app/cards/detail.html
{% extends "app/base.html" %}

{% block content %}

<h1>タスク詳細</h1>
<dl class="row">
  <dt class="col-sm-3">タイトル</dt>
  <dd class="col-sm-9">{{ card.title }}</dd>
  <dt class="col-sm-3">詳細</dt>
  <dd class="col-sm-9">{{ card.description }}</dd>
  <dt class="col-sm-3">リスト名</dt>
  <dd class="col-sm-9">{{ card.list.title }}</dd>
  <dt class="col-sm-3">ユーザー名</dt>
  <dd class="col-sm-9">{{ card.user.username }}</dd>
</dl>

<a class="btn btn-primary" href="{% url 'app:cards_update' card.pk %}" role="button">編集</a>
<a class="btn btn-danger" href="{% url 'app:cards_delete' card.pk %}" role="button">削除</a>

{% endblock %}

project/app/templates/app/cards/list.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>タスク一覧</h1>
  <a class="btn btn-primary my-3" href="{% url 'app:cards_create' %}" role="button">作成</a>
  <div class="card-columns">
    {% for card in card_list %}
    <a href="{% url 'app:cards_detail' card.pk %}" class="card">
      <div class="card-body">
        <h5 class="card-title">{{ card.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ card.user.username }}</small>
        </footer>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

project/app/templates/app/cards/update.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>タスク編集</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

project/app/templates/app/home.html
{% extends "app/base.html" %}

{% block content %}
<div class="container-fluid home">
  <h1>タスク一覧</h1>
  <div class="row flex-nowrap">
    {% for list in list_list %}
    <div class="bg-light m-3 p-2 list">
      <h4>{{ list.title }}
        <a href="{% url 'app:lists_update' list.pk %}" class="text-dark"><i class="far fa-edit fa-xs"></i></a>
        <a href="{% url 'app:lists_delete' list.pk %}" class="text-dark"><i class="far fa-trash-alt fa-xs"></i></a>
      </h4>

      {% for card in list.card_set.all %}
      <a href="{% url 'app:cards_detail' card.pk %}" class="card m-3">
        <div class="card-body">
          <h5 class="card-title">{{ card.title }}</h5>
          <footer>
            <small class="text-muted">作成者: {{ card.user.username }}</small>
          </footer>
        </div>
      </a>
      {% endfor %}
      <a href="{% url 'app:cards_create_from_home' list.pk %}" class="text-dark"><i class="far fa-plus-square"></i> さらにカードを追加</a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">TODO-Share</h1>
  <p class="lead">ToDo-Shareでタスク管理をしてみましょう。</p>
  <hr class="my-4">
  <p>このアプリケーションはDjangoで作られています。</p>
  <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">ログイン</a>
  <a class="btn btn-primary btn-lg" href="{% url 'app:signup' %}" role="button">サインアップ</a>
</div>
{% endblock %}

project/app/templates/app/lists/create.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

project/app/templates/app/lists/delete.html
{% extends "app/base.html" %}

{% block content %}
<h1>リスト削除</h1>
<form method="post">
  {% csrf_token %}
  <p>リスト "{{ list.title }}" を本当に削除してもよろしいですか？</p>
  <button type="submit" class="btn btn-danger">確認</button>
</form>
{% endblock %}

project/app/templates/app/lists/detail.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト詳細</h1>
  <dl class="row">
    <dt class="col-sm-3">タイトル</dt>
    <dd class="col-sm-9">{{ list.title }}</dd>
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ list.user.username }}</dd>
  </dl>

  <a class="btn btn-primary" href="{% url 'app:lists_update' list.pk %}" role="button">編集</a>
  <a class="btn btn-danger" href="{% url 'app:lists_delete' list.pk %}" role="button">削除</a>
</div>
{% endblock %}

project/app/templates/app/lists/list.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト一覧</h1>
  <a class="btn btn-primary my-3" href="{% url 'app:lists_create' %}" role="button">作成</a>
  <div class="card-columns">
    {% for list in list_list %}
    <a href="{% url 'app:lists_detail' list.pk %}" class="card">
      <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ list.user.username }}</small>
        </footer>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

project/app/templates/app/lists/update.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト編集</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

project/app/templates/app/signup.html
{% extends "app/base.html" %}

{% block content %}
  <div class="container">
    <h1>サインアップ</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">登録</button>
    </form>
  </div>
{% endblock %}

project/app/templates/app/users/delete.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>退会</h1>
  <form method="post">
    {% csrf_token %}
    <p>あなたのアカウント 「@{{ user.username }}」 を、本当に削除してもよろしいでしょうか？</p>
    <button type="submit" class="btn btn-danger">削除</button>
    <a href="{% url 'app:users_detail' user.pk %}" class="btn btn-primary">キャンセル</a>
  </form>
</div>
{% endblock %}

project/app/templates/app/users/detail.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー詳細</h1>
  <dl class="row">
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ user.username }}</dd>
    <dt class="col-sm-3">姓</dt>
    <dd class="col-sm-9">{{ user.last_name }}</dd>
    <dt class="col-sm-3">名</dt>
    <dd class="col-sm-9">{{ user.first_name }}</dd>
    <dt class="col-sm-3">メールアドレス</dt>
    <dd class="col-sm-9">{{ user.email }}</dd>
  </dl
  {% if user.pk == request.user.pk %}
    <a class="btn btn-primary"></a>
    <a class="btn btn-primary" href="{% url 'app:users_update' user.pk %}" role="button">編集</a>
    <a class="btn btn-danger" href="{% url 'app:users_delete' user.pk %}" role="button">退会</a>
  {% else %}
    <a class="btn btn-primary"></a>
    <a class="btn btn-primary disabled" href="#" role="button">編集</a>
    <a class="btn btn-danger disabled" href="#" role="button">退会</a>
  {% endif %}
</div>
{% endblock %}

project/app/templates/app/users/update.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー編集</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}